# Generated by Django 4.2 on 2023-04-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_group',
            name='source',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('s', '单选'), ('i', '不定项'), ('m', '多媒体')], default='i', max_length=10),
        ),
        migrations.AlterField(
            model_name='question_group',
            name='subject',
            field=models.CharField(choices=[('g', '地理'), ('e', '地球科学')], default='e', max_length=10),
        ),
    ]
