# Generated by Django 4.2 on 2023-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_group_source_alter_question_q_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='question_group',
            name='img',
            field=models.CharField(default='', max_length=20),
        ),
    ]
